export default {
  Alt: 'Alt',
  Ambient: 'Ambient',
  Baroque: 'Baroque',
  Blues: 'Blues',
  Charts: 'Charts',
  Chill: 'Chill',
  Classical: 'Classical',
  Community: 'Community',
  Contemporary: 'Contemporary',
  Country: 'Country',
  Dance: 'Dance',
  Disco: 'Disco',
  Dubstep: 'Dubstep',
  EDM: 'EDM',
  Electronic: 'Electronic',
  Funk: 'Funk',
  Gaming: 'Gaming',
  Hiphop: 'Hip-Hop',
  Indie: 'Indie',
  Jazz: 'Jazz',
  Lofi: 'Lofi',
  Podcast: 'Podcast',
  Pop: 'Pop',
  Progressive: 'Progressive',
  Rap: 'Rap',
  Reggae: 'Reggae',
  RNB: 'R&B',
  Rock: 'Rock',
  Romantic: 'Romantic',
  Simulation: 'Simulation',
  SleepSounds: 'Sleep Sounds',
  Soul: 'Soul',
  TalkShow: 'Talk Show',
  Trap: 'Trap'
}